yo yo sths working
OatmealLick/lighthouse-sim pull request #1
Opened 2018-03-20 18:41 UTC by OatmealLick

2018-03-20 18:55 UTC, Bzdeco requested changes

2018-03-20 18:55 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/MovementSensorBuilder.java
> +    private double radius = -1;
Will be set to 0 automatically without this assignments, so I guess it's unnecessary.

2018-03-20 18:55 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/MovementSensorBuilder.java
> +    private boolean sensingMovement = false;
Will be set to `false` automatically.

2018-03-20 18:55 UTC, Bzdeco commented on src/main/java/org/wingtree/simulation/Simulation.java
> +                + actor.getVelocity()/1000 * interval;
I guess this is because interval is in milliseconds and velocity is in m/s, but I think it is not clear enough

2018-03-20 18:55 UTC, Bzdeco commented on src/main/java/org/wingtree/util/Algebra.java
> +        return radius > distanceBetweenCoords;
I think `>=` is better - it is more intuitive if a camera with range 2m detects objects also at 2m rather than at 2m - epsilon :smile:

2018-03-20 18:55 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/CameraBuilder.java
> +    private double radius = -1;
Could be simply defaultly set to 0 without assignment

2018-03-20 18:55 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/InternalActor.java
> +    private final double velocity;
Does it need to be so precise? :stuck_out_tongue:

2018-03-20 18:55 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/StartupParameters.java
> +                .withActorsInView(Sets.newHashSet())
No reason to do this twice, as it is set to empty set in class definition

2018-03-20 18:55 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/TrackingDevice.java
> +    void updateState(Coords trackingDeviceCoords, Set<InternalActor> actors);
Will we ever need to update `trackingDeviceCoords` after creating one with a builder?

2018-03-20 21:36 UTC, OatmealLick commented on src/main/java/org/wingtree/beans/TrackingDevice.java
> +    void updateState(Coords trackingDeviceCoords, Set<InternalActor> actors);
this is fucked-up-interface issue. TrackingDevice doesn't know about its coords, only lantern does

2018-03-20 21:40 UTC, OatmealLick commented on src/main/java/org/wingtree/beans/StartupParameters.java
> +                .withActorsInView(Sets.newHashSet())
removed

2018-03-20 21:41 UTC, OatmealLick commented on src/main/java/org/wingtree/beans/InternalActor.java
> +    private final double velocity;
its not about being precise. It's because for some reason I started to use my own algebra instead of using some library, and all methods from `Math` class are returning doubles. Casting every single time was killing me as well as killing those additional decimal places. I decided to keep them and made every floating point var a double

2018-03-20 21:41 UTC, OatmealLick commented on src/main/java/org/wingtree/beans/CameraBuilder.java
> +    private double radius = -1;
changed

2018-03-20 21:42 UTC, OatmealLick commented on src/main/java/org/wingtree/util/Algebra.java
> +        return radius > distanceBetweenCoords;
changed

2018-03-20 21:47 UTC, OatmealLick commented on src/main/java/org/wingtree/simulation/Simulation.java
> +                + actor.getVelocity()/1000 * interval;
ok, ill think of sth better, not gonna waste too much time tho

2018-03-20 21:51 UTC, OatmealLick commented on src/main/java/org/wingtree/beans/MovementSensorBuilder.java
> +    private boolean sensingMovement = false;
removed

2018-03-20 21:51 UTC, OatmealLick commented on src/main/java/org/wingtree/beans/MovementSensorBuilder.java
> +    private double radius = -1;
removed

2018-03-20 21:55 UTC, OatmealLick commented on src/main/java/org/wingtree/beans/TrackingDevice.java
> +    void updateState(Coords trackingDeviceCoords, Set<InternalActor> actors);
I dunno man, it feels wrong but this project is so small, that major changes to project are not that scary. I am leaving this for now, we can get back to this once we have time.

2018-03-20 22:02 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/InternalActor.java
> +    private final double velocity;
Ok :+1:

2018-03-20 22:05 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/TrackingDevice.java
> +    void updateState(Coords trackingDeviceCoords, Set<InternalActor> actors);
I still don't get it - since `TrackingDevice` has no clue of the coords, why we need to pass it as argument in its method?
Yeah, changes in this can be done later (never), but I just want to understand it :grinning:

2018-03-22 16:02 UTC, OatmealLick commented on src/main/java/org/wingtree/beans/TrackingDevice.java
> +    void updateState(Coords trackingDeviceCoords, Set<InternalActor> actors);
what do I need to update tracking device? Let's say it's movement sensor, which has boolean field which should be true when someone is in range. Let's list things we need to update its state:
* actor coords
* sensor coords
* sensor range

Every implementation of TrackingDevice had radius, we get actors as arguments where can we get trancking device coords from? We should get it as argument right?

2018-03-22 16:14 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/TrackingDevice.java
> +    void updateState(Coords trackingDeviceCoords, Set<InternalActor> actors);
Tracking device should have fixed coords since it creation and they should be the same as the lantern it is attached to. Tracking device don't move or change the lanterns that hold them.

2018-03-22 16:18 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/TrackingDevice.java
> +    void updateState(Coords trackingDeviceCoords, Set<InternalActor> actors);
In other words - every implementation of TrackingDevice should probably have it's coords and radius.

2018-03-22 16:19 UTC, OatmealLick commented on src/main/java/org/wingtree/beans/TrackingDevice.java
> +    void updateState(Coords trackingDeviceCoords, Set<InternalActor> actors);
and lanterns should be removed from the game

2018-03-22 16:21 UTC, Bzdeco commented on src/main/java/org/wingtree/beans/TrackingDevice.java
> +    void updateState(Coords trackingDeviceCoords, Set<InternalActor> actors);
Not really, they are the nodes of the graph on which the objects are moving, they represent junctions. They are needed for determining what is the next goal point for the object (including this goal point's coords). Optionally there is a possibility of a "lantern"/junction with no devices attached.

2018-03-22 16:38 UTC, Bzdeco commented on src/main/java/org/wingtree/simulation/Simulation.java
> +                + actor.getVelocityInMetersPerSec() * convertToSeconds(intervalInMillis);
:+1:

2018-03-25 13:54 UTC, closed without merging